### ISSUE TITLE
internal参数未生效

### ISSUE THREAD

**Issue by sunhaolin** [yyang/cfs-aliyun#6]
已确认服务所在服务器和附件所在服务器为同一内网服务器 “华北2”，
var ossStore = new Aliyun.OSS(serviceParams); 中serviceParams为：
{
    accessKeyId: 'xxxxxx',
    secretAccessKey: 'xxxxxx',
    endpoint: 'http://oss-cn-beijing-internal.aliyuncs.com',
    timeout: 60000,
    apiVersion: '2013-10-15',
    region: 'oss-cn-beijing',
    internal: true,
    bucket: 'testbucket',
    folder: undefined 
}
但是设置internal参数后，上传和下载都不行。

不知各位是否遇到过这样的问题?

**Comment by sunhaolin** [comment]
1、因为设置了internal参数值为true后，createWriteStream: function(fileKey, options) 参数fileKey 和options都与internal值为false时格式不一样：
 internal为false时 fileKey值"xxxxx.jpg" options值为{xxx:xxx, yyy:yyy};
 internal为true时 fileKey值{a:a,b:b} options值为undefined, 这样会导致 Key的值为 "[object object]"；
2、猜测很可能是因为 FS.StorageAdapter 中 self.adapter.createReadStream 方法里根据self.internal返回不同的值导致，还未证实。
目前解决方法 是配置时不用internal了，直接用 "region" : "oss-cn-beijing-internal"，并注释掉FS.Store.OSS invalid region相关代码。

**Comment by yyang** [comment]
Thanks. Let me fix it.

Sent from my iPhone

On Jul 17, 2016, at 12:15 AM, sunhaolin <notifications@github.com<mailto:notifications@github.com>> wrote:

1$B!"0x(B??$BCVN;(Binternal$B;2?t(B??true$B9!!$(BcreateWriteStream: function(fileKey, options) $B;2?t(BfileKey $BOB(Boptions$BETM?(Binternal??false?$B3J<0IT0l(B?$B!'(B
internal?false? fileKey?"xxxxx.jpg" options??{xxx:xxx, yyy:yyy};
internal?true? fileKey?{a:a,b:b} options??undefined, ??$B2q(B?$BCW(B Key$BE*(B?? "[object object]"$B!((B
2$B!"`J(B?$BWL2DG=@'0x(B? FS.StorageAdapter $BCf(B self.adapter.createReadStream $BJ}K!N$:,?x(Bself.internal$BJV2sITF1E*(B??$BCW!$(B?$BL$(B??$B!#(B
$BL\A02rQSJ}K!(B $B@'G[CV(B?$BITMQ(Binternal$BN;!$D>@\MQ(B "region" : "oss-cn-beijing-internal"$B!$VuCm(B?$BY\(BFS.Store.OSS invalid region$BAj(B?$BBe(B?

##

**Comment by sunhaolin** [comment]
这样改我测试过aliyunInternal 参数是不生效的， 在FS.Store.OSS = function(name, options) 方法中console.log(options) 中是没有aliyunInternal这个参数的。
猜测参数的名称FS会过滤，还未确认。

**Comment by yyang** [comment]
?$B!$2fpQ!$(B?$BE*(B

Sent from my iPhone

On Jul 18, 2016, at 10:33 AM, sunhaolin <notifications@github.com<mailto:notifications@github.com>> wrote:

??$B2~2f(B???aliyunInternal $B;2?t@'IT@8ZCE_!$(B $B:_(BFS.Store.OSS = function(name, options) $BJ}K!Cf(Bconsole.log(options) $BCf@'KWM-(BaliyunInternal?$BP$;2?tE_!#(B
$B`J(B?$B;2?tE*L>>N(BFS$B2q(B??$B!$(B?$BL$(B??$B!#(B

##

**Comment by yyang** [comment]
$BFa2f2C(Bregion$B;;N;(B

Sent from my iPhone

On Jul 18, 2016, at 10:33 AM, sunhaolin <notifications@github.com<mailto:notifications@github.com>> wrote:

??$B2~2f(B???aliyunInternal $B;2?t@'IT@8ZCE_!$(B $B:_(BFS.Store.OSS = function(name, options) $BJ}K!Cf(Bconsole.log(options) $BCf@'KWM-(BaliyunInternal?$BP$;2?tE_!#(B
$B`J(B?$B;2?tE*L>>N(BFS$B2q(B??$B!$(B?$BL$(B??$B!#(B

##

**Comment by sunhaolin** [comment]
乱码。。。

**Comment by yyang** [comment]
我是说，卧槽那我干脆直接改region？

**Comment by sunhaolin** [comment]
额，这FS也是有点坑

**Comment by streamliner18** [comment]
有没有办法直接提供一个endpoint option? 觉得这样可能比较hands-on 而且顺便把我之前提过region check的问题也解决了

**Comment by streamliner18** [comment]
@sunhaolin 看起来不像会过滤啊 options是直接传给new FS.Store.OSS的，我挂下来加几个console log再看看

**Comment by yyang** [comment]
@wxhemiao 我已经发了shanghai那个了。那我加新的挂载点吧。

**Comment by streamliner18** [comment]
@yyang @sunhaolin Eh it looks fine with aliyunInternal. Endpoint is correct and proven working (Uploads fine on ECS and not on local). I'm on Meteor 1.3.2.4. Keen to know what's your version?

**Comment by streamliner18** [comment]
@yyang Propose一个想法，能不能在初始化的时候戳一下那个aliyun-internal的服务器来确定是不是在ECS上运行。如果是的话自动优先用internal endpoint。这个方法可能有点笨拙，但是对阿里云不太熟，我知道AWS EC2上有个特殊地址169.254.169.254可以用来判断是否在EC2上运行，不知道ECS能不能同样这么做

**Comment by yyang** [comment]
@sunhaolin @wxhemiao Could you please help me confirm if `aliyunInternal` option works?

**Comment by sunhaolin** [comment]
@yyang @wxhemiao 
1、我的版本Meteor 1.2.1；
2、aliyunInternal 被过滤：
     我配置了以下的options用于new FS.Store.OSS
{
  "region" : "oss-cn-beijing",
  "bucket" : "xxx",
  "accessKeyId" : "xxx",
  "secretAccessKey" : "xxxxxx",
  "aliyunInternal" : "test",
  "folder" : "test"
}
但是 打印出的options却是：
{ 
  region: 'oss-cn-beijing',
  internal: undefined,
  bucket: 'xxx',
  folder: 'test',
  accessKeyId: 'xxx',
  secretAccessKey: 'xxxxxx' 
}
可以看到 folder 属性是有了，但是aliyunInternal没有。
你们console出来的是什么？btw:试了下cfs:s3 也是这样

**Comment by streamliner18** [comment]
@sunhaolin 我直接intercept这个option里面有，以及在Shell查询FS.Collection的primaryStore属性里也能看到这个`aliyunInternal: true`

我在本地加production flag运行以后用Charles截获数据包证实是访问了internal节点。(Meteor 1.3.2.4 osx.x86_64)

**Comment by streamliner18** [comment]
@sunhaolin 你是不是没有更新这个模块？

`meteor update iyyang:cfs-aliyun`

**Comment by sunhaolin** [comment]
@yyang @wxhemiao 非常抱歉  我SB了，原来是我根本没传aliyunInternal，好尴尬

**Comment by sunhaolin** [comment]
@yyang @wxhemiao 请教个问题，我现在有个下载附件的链接在a标签的href属性，点击a标签调用下载附件接口，接口是用 readStream.pipe(writeStream) 返回附件的，但是当我在浏览器非常快速的连续点击多次后下载就一直在等待，其实是下载不了了，你们碰到过这种情况吗？

**Comment by streamliner18** [comment]
为啥是这个接口…我一直用的{{this.url}}和html5 download attr

发自我的 iPhone

**Comment by streamliner18** [comment]
@yyang Yo finally you can close this one 😆 Looks like your pkg finally gets some serious users to test it!

**Comment by yyang** [comment]
Great thanks all!

**Comment by sunhaolin** [comment]
@wxhemiao 其实就是collectionfs 点击`<a href={{this.url}} >{{this.name}}</a>` 下载的，然后突然发现非常快的连续点击之后浏览器就一直在等待

**Comment by sunhaolin** [comment]
@wxhemiao  thank you very much, for the html5 download attr.
